### ISSUE TITLE
`export': wrong number of arguments (2 for 1) (ArgumentError)

### ISSUE THREAD

**Issue by muranava** [markolson/storyboard#18]
getting this error message when running scene skip -k option

/Users/mura/.rvm/gems/ruby-2.1.2/gems/titlekit-1.2.0/lib/titlekit/parsers/ass.rb:131:in `export': wrong number of arguments (2 for 1) (ArgumentError)

**Comment by markolson** [comment]
This may be fixed with 899c1c74236b501d00aefe36a519f1b6aed2260f, if you can try a `git pull` and `bundle install`

**Comment by muranava** [comment]
great thanks manged to produce a pdf with skip scene option
